/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var regexp = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,11],$V1=[1,12],$V2=[1,8],$V3=[1,16],$V4=[1,17],$V5=[1,13],$V6=[1,14],$V7=[1,15],$V8=[1,18],$V9=[1,4,27],$Va=[1,4,7,12,13,15,26,27,28,30,31,45],$Vb=[1,4,7,12,13,15,18,19,20,22,26,27,28,30,31,45],$Vc=[1,36],$Vd=[1,37],$Ve=[1,31],$Vf=[1,32],$Vg=[1,33],$Vh=[15,33,38,40,42,47],$Vi=[1,47],$Vj=[15,33,36,38,40,42,47],$Vk=[1,4,7,27],$Vl=[39,41];
var parser = {trace: function trace () {
        Jison.print.apply(null, arguments);
    },
yy: {},
symbols_: {"error":2,"pattern":3,"EOF":4,"sequential":5,"alternative":6,"PIPE":7,"basic":8,"repeatable":9,"repetition":10,"anchor":11,"BOS":12,"EOS":13,"atomic":14,"ESCAPED":15,"class":16,"group":17,"OPT":18,"STAR":19,"PLUS":20,"count":21,"COUNT_OPEN":22,"COUNT_NUMBER":23,"COUNT_CLOSE":24,"COUNT_COMMA":25,"CAPTURING_GROUP_OPEN":26,"GROUP_CLOSE":27,"NON_CAPTURING_GROUP_OPEN":28,"COLON":29,"DOT":30,"CHAR":31,"member_symbol":32,"MEMBER_CHAR":33,"member_chars":34,"member_range":35,"MEMBER_DASH":36,"member":37,"MEMBER_POSIX_OPEN":38,"MEMBER_POSIX_CLOSE":39,"MEMBER_COLLATING_OPEN":40,"MEMBER_COLLATING_CLOSE":41,"MEMBER_EQUIVALENCE_OPEN":42,"MEMBER_EQUIVALENCE_CLOSE":43,"members":44,"CLASS_OPEN":45,"MEMBER_NEGATION":46,"CLASS_CLOSE":47,"$accept":0,"$end":1},
terminals_: {2:"error",4:"EOF",7:"PIPE",12:"BOS",13:"EOS",15:"ESCAPED",18:"OPT",19:"STAR",20:"PLUS",22:"COUNT_OPEN",23:"COUNT_NUMBER",24:"COUNT_CLOSE",25:"COUNT_COMMA",26:"CAPTURING_GROUP_OPEN",27:"GROUP_CLOSE",28:"NON_CAPTURING_GROUP_OPEN",29:"COLON",30:"DOT",31:"CHAR",33:"MEMBER_CHAR",36:"MEMBER_DASH",38:"MEMBER_POSIX_OPEN",39:"MEMBER_POSIX_CLOSE",40:"MEMBER_COLLATING_OPEN",41:"MEMBER_COLLATING_CLOSE",42:"MEMBER_EQUIVALENCE_OPEN",43:"MEMBER_EQUIVALENCE_CLOSE",45:"CLASS_OPEN",46:"MEMBER_NEGATION",47:"CLASS_CLOSE"},
productions_: [0,[3,2],[3,1],[3,1],[6,3],[6,3],[5,1],[5,2],[8,2],[8,1],[8,1],[11,1],[11,1],[9,1],[9,1],[9,1],[9,1],[10,1],[10,1],[10,1],[10,1],[21,3],[21,4],[21,5],[17,3],[17,4],[14,1],[14,1],[32,1],[32,1],[34,1],[34,2],[35,3],[37,3],[37,3],[37,3],[37,1],[37,1],[44,1],[44,2],[16,4],[16,3]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
console.log(JSON.stringify(						this.$		,null,4	))	
break;
case 2: case 3: case 9: case 10: case 13: case 15: case 16: case 20: case 30: case 36:
this.$	=												$$[$0]					
break;
case 4:
this.$ = c	([],'alternative'			,			$$[$0-2],		$$[$0]			)	
break;
case 5:
$$[$0-2].push(											$$[$0]				)	
break;
case 6:
this.$	= c	([],'sequential'			,				$$[$0]				)	
break;
case 7: case 39:
$$[$0-1].push(											$$[$0]				)	
break;
case 8:
this.$	= c	({},'repeating'				,			$$[$0-1],		$$[$0]			)	
break;
case 11: case 12:
this.$	= c	({},'anchor'				,				$$[$0]				)	
break;
case 14:
this.$	= c	({},'escaped'				,				$$[$0]				)	
break;
case 17: case 18: case 19:
this.$	= c	({},'repeatition'			,				$$[$0]				)	
break;
case 21:
this.$	= c	({},'count'					,		$$[$0-2],	$$[$0-1],			$$[$0]		)	
break;
case 22:
this.$	= c	({},'count'					,		$$[$0-3],	$$[$0-2],	$$[$0-1],		$$[$0]		)	
break;
case 23:
this.$	= c	({},'count'					,		$$[$0-4],	$$[$0-3],	$$[$0-2],	$$[$0-1],	$$[$0]		)	
break;
case 24:
this.$	= c	({},	'capturing_group'	,		$$[$0-2],		$$[$0-1],	$$[$0]			)	
break;
case 25:
this.$	= c	({},'non_capturing_group'	,		$$[$0-3]+	$$[$0-2],	$$[$0-1],	$$[$0]			)	
break;
case 26:
this.$	= c	({},'DOT'					,				$$[$0]				)	
break;
case 27:
this.$	= c	({},'CHAR'					,				$$[$0]				)	
break;
case 28:
this.$	= c	({},'ESCAPED'				,				$$[$0]				)	
break;
case 29:
this.$	= c	({},'MEMBER_CHAR'			,				$$[$0]				)	
break;
case 31:
this.$	=											$$[$0-1]+	$$[$0]					
break;
case 32:
this.$	= c	({},'member_range'			,			$$[$0-2],	$$[$0-1],	$$[$0]			)	
break;
case 33:
this.$	= c	({},'MEMBER_POSIX'			,			$$[$0-2],	$$[$0-1],	$$[$0]			)	
break;
case 34:
this.$	= c	({},'MEMBER_COLLATING'		,			$$[$0-2],	$$[$0-1],	$$[$0]			)	
break;
case 35:
this.$	= c	({},'MEMBER_EQUIVALENCE'	,			$$[$0-2],	$$[$0-1],	$$[$0]			)	
break;
case 37:
this.$	= c	({},'member_symbol'			,				$$[$0]				)	
break;
case 38:
this.$	= c	([],'members'				,				$$[$0]				)	
break;
case 40:
this.$	= c	({},'negative_class'		,	$$[$0-3]+	$$[$0-2],	...	$$[$0-1], $$[$0]			)	
break;
case 41:
this.$	= c	({},'positive_class'		,	$$[$0-2],		...	$$[$0-1],	$$[$0]			)	
break;
}
},
table: [{3:1,5:2,6:3,8:4,9:5,11:6,12:$V0,13:$V1,14:7,15:$V2,16:9,17:10,26:$V3,28:$V4,30:$V5,31:$V6,45:$V7},{1:[3],4:$V8},o($V9,[2,2],{9:5,11:6,14:7,16:9,17:10,8:19,7:[1,20],12:$V0,13:$V1,15:$V2,26:$V3,28:$V4,30:$V5,31:$V6,45:$V7}),o($V9,[2,3],{7:[1,21]}),o($Va,[2,6]),o($Va,[2,9],{10:22,21:26,18:[1,23],19:[1,24],20:[1,25],22:[1,27]}),o($Va,[2,10]),o($Vb,[2,13]),o($Vb,[2,14]),o($Vb,[2,15]),o($Vb,[2,16]),o($Va,[2,11]),o($Va,[2,12]),o($Vb,[2,26]),o($Vb,[2,27]),{15:$Vc,32:35,33:$Vd,35:34,37:30,38:$Ve,40:$Vf,42:$Vg,44:29,46:[1,28]},{3:38,5:2,6:3,8:4,9:5,11:6,12:$V0,13:$V1,14:7,15:$V2,16:9,17:10,26:$V3,28:$V4,30:$V5,31:$V6,45:$V7},{29:[1,39]},o($V9,[2,1]),o($Va,[2,7]),{5:40,8:4,9:5,11:6,12:$V0,13:$V1,14:7,15:$V2,16:9,17:10,26:$V3,28:$V4,30:$V5,31:$V6,45:$V7},{5:41,8:4,9:5,11:6,12:$V0,13:$V1,14:7,15:$V2,16:9,17:10,26:$V3,28:$V4,30:$V5,31:$V6,45:$V7},o($Va,[2,8]),o($Va,[2,17]),o($Va,[2,18]),o($Va,[2,19]),o($Va,[2,20]),{23:[1,42]},{15:$Vc,32:35,33:$Vd,35:34,37:30,38:$Ve,40:$Vf,42:$Vg,44:43},{15:$Vc,32:35,33:$Vd,35:34,37:45,38:$Ve,40:$Vf,42:$Vg,47:[1,44]},o($Vh,[2,38]),{33:$Vi,34:46},{33:$Vi,34:48},{33:[1,49]},o($Vh,[2,36]),o($Vh,[2,37],{36:[1,50]}),o($Vj,[2,28]),o($Vj,[2,29]),{4:$V8,27:[1,51]},{3:52,5:2,6:3,8:4,9:5,11:6,12:$V0,13:$V1,14:7,15:$V2,16:9,17:10,26:$V3,28:$V4,30:$V5,31:$V6,45:$V7},o($Vk,[2,4],{9:5,11:6,14:7,16:9,17:10,8:19,12:$V0,13:$V1,15:$V2,26:$V3,28:$V4,30:$V5,31:$V6,45:$V7}),o($Vk,[2,5],{9:5,11:6,14:7,16:9,17:10,8:19,12:$V0,13:$V1,15:$V2,26:$V3,28:$V4,30:$V5,31:$V6,45:$V7}),{24:[1,53],25:[1,54]},{15:$Vc,32:35,33:$Vd,35:34,37:45,38:$Ve,40:$Vf,42:$Vg,47:[1,55]},o($Vb,[2,41]),o($Vh,[2,39]),{39:[1,56]},o($Vl,[2,30],{34:57,33:$Vi}),{41:[1,58]},{43:[1,59]},{15:$Vc,32:60,33:$Vd},o($Vb,[2,24]),{4:$V8,27:[1,61]},o($Va,[2,21]),{23:[1,63],24:[1,62]},o($Vb,[2,40]),o($Vh,[2,33]),o($Vl,[2,31]),o($Vh,[2,34]),o($Vh,[2,35]),o($Vh,[2,32]),o($Vb,[2,25]),o($Va,[2,22]),{24:[1,64]},o($Va,[2,23])],
defaultActions: {},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

	function throwing(e){throw e}
	// excerpt from bluelephant_tk.js verbatim begin
			; /** provides class / makes classy (the old fashioned way)
				*/					function	 higgins  (	prototype,			constructor,methods)
				{if(										prototype)			constructor
					.										prototype
					=										prototype
				;for(var																	method
					in																		methods
					)															constructor
					.										prototype
						[																	methods
							[																method].name]
					=																		methods
						[																	method]
	// excerpt from bluelephant_tk.js verbatim end
				;					return										constructor}
				;					function	     make	(		constructor								,_argument____	){	var	result;			constructor. prototype.		constructor=constructor;if(Object.create)result=Object.create(constructor.prototype);else	if((result={}).__proto__=constructor.prototype,result.__proto__!==constructor.prototype)(result=function(){},result.name=constructor.name,result).prototype=constructor.prototype // the first instruction was (before 220730) $b.dflt but that didn't work in practice and seems wrong in theory, as there always already exists a constructor on any object, right?
						;																																			return(			$b				.proxcall(			result							,	arguments,constructor	,1)||result)} // thanks http://stackoverflow.com/users/157247/t-j-crowder @ http://stackoverflow.com/a/3871769/620603#620603
	// excerpt from bluelephant_tk.js changed function context from array (arg to methodize) begin
			;						function	 higginstr(	prototype,	name,	constructor,methods)
				{									   'string'==typeof	name
				&&														name.match(/^\w*$/)
				||										  null===		name
				||									 undefined===		name
				||throwing(new Error('Illeagal constructor name: '+		name))
				;return							 higgins  (	prototype
					,	(			function			  (				name,	constructor)
						{			return		 eval	  ('\
							(		function'+(							name
								?' '+									name:'')+'\
							  (){												constructor																.apply\
								(	this\
								, [	this].concat(														[].slice.call(arguments)))})')})
						(												name,	constructor)
					,																		methods)}
	// excerpt from bluelephant_tk.js changed function context from array (arg to methodize) end
			;function c									  (	prototype,	name,													piece___)
				{return							     make																								.apply
					(							 higginstr(	prototype,	name,function(											piece___){	this.concat	.apply
								(																											this
								,																								piece___)}
						,	[		])
					,																					[].slice.call(arguments,2))}
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return 4
break;
case 1:this.begin('s_escape')
break;
case 2:
								this.popState()
								return 15
								
break;
case 3:return 12
break;
case 4:return 29
break;
case 5:return 28
break;
case 6:return 26
break;
case 7:return 27
break;
case 8:return 46
break;
case 9:return 38
break;
case 10:return 40
break;
case 11:return 42
break;
case 12:return 43
break;
case 13:return 41
break;
case 14:return 39
break;
case 15:return 36
break;
case 16:return 33
break;
case 17:
								this.begin('s_class')
								return 45
								
break;
case 18:
								this.popState()
								return 47
								
break;
case 19:
								this.begin('s_count')
								return 22
								
break;
case 20:return 23
break;
case 21:return 25
break;
case 22:
								this.popState()
								return 24
								
break;
case 23:return 30
break;
case 24:return 19
break;
case 25:return 18
break;
case 26:return 20
break;
case 27:return 7
break;
case 28:return 13
break;
case 29:return 31
break;
}
},
rules: [/^(?:$)/,/^(?:\\)/,/^(?:.)/,/^(?:\^)/,/^(?::)/,/^(?:\(\?)/,/^(?:\()/,/^(?:\))/,/^(?:\^)/,/^(?:\[:)/,/^(?:\[\.)/,/^(?:\[=)/,/^(?:=\])/,/^(?:\.\])/,/^(?::\])/,/^(?:-)/,/^(?:[^\]\\])/,/^(?:\[)/,/^(?:\])/,/^(?:\{)/,/^(?:[0-9]+)/,/^(?:,)/,/^(?:\})/,/^(?:\.)/,/^(?:\*)/,/^(?:\?)/,/^(?:\+)/,/^(?:\|)/,/^(?:\$)/,/^(?:[^^(?:.*|\[+){$\\])/],
conditions: {"s_escape":{"rules":[2],"inclusive":true},"s_count":{"rules":[20,21,22],"inclusive":true},"s_class":{"rules":[1,8,9,10,11,12,13,14,15,16,18],"inclusive":true},"INITIAL":{"rules":[0,1,3,4,5,6,7,17,19,23,24,25,26,27,28,29],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = regexp;
exports.Parser = regexp.Parser;
exports.parse = function () { return regexp.parse.apply(regexp, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}